exports.seed = function (knex, Promise) {
  return knex('users').insert([
    { id: 99901, name: 'Ambitious Aardvark', username: 'Aardvark' , profileLink: "www.steam.com/user_id/Aardvark"},
    { id: 99902, name: 'Bamboozled Baboon', username: 'Baboon', profileLink: "www.steam.com/user_id/Baboon"},
    { id: 99903, name: 'Curious Capybara', username: 'Capybara' , profileLink: "www.steam.com/user_id/Capybara"},
    { id: 99904, name: 'Dilapidated Duck', username: 'Duck' , profileLink: "www.steam.com/user_id/Duck"},
    { id: 99905, name: 'Exuberant Elephant', username: 'Elephant' , profileLink: "www.steam.com/user_id/Elephant"},
    { id: 99906, name: 'Fascinated Flying Fox', username: 'Fox' , profileLink: "www.steam.com/user_id/Fox"},
    { id: 99907, name: 'Generous Gila Monster', username: 'Gila' , profileLink: "www.steam.com/user_id/Monster"},
    { id: 99908, name: 'Hilarious Heron', username: 'Heron' , profileLink: "www.steam.com/user_id/Heron"},
    { id: 99909, name: 'Intransigent Impala', username: 'Impala' , profileLink: "www.steam.com/user_id/Impala"},
    { id: 99910, name: 'Jocular Jerboa', username: 'Jerboa' , profileLink: "www.steam.com/user_id/Jerboa"},
    { id: 99911, name: 'Kafkaesque Kinkajou', username: 'Kinkajou' , profileLink: "www.steam.com/user_id/Kinkajou"},
    { id: 99912, name: 'Loquacious Lemur', username: 'Lemur' , profileLink: "www.steam.com/user_id/Lemur"},
    { id: 99913, name: 'Misanthropic Mongoose', username: 'Mongoose' , profileLink: "www.steam.com/user_id/Mongoose"},
    { id: 99914, name: 'Nonchalant Nyala', username: 'Nyala' , profileLink: "www.steam.com/user_id/Nyala"},
    { id: 99915, name: 'Ornery Ocelot', username: 'Ocelot' , profileLink: "www.steam.com/user_id/Ocelot"},
    { id: 99916, name: 'Peaceful Pangolin', username: 'Pangolin' , profileLink: "www.steam.com/user_id/Pangolin"},
    { id: 99917, name: 'Querulous Quokka', username: 'Quokka' , profileLink: "www.steam.com/user_id/Quokka"},
    { id: 99918, name: 'Resolute Rail', username: 'Rail' , profileLink: "www.steam.com/user_id/Rail"},
    { id: 99919, name: 'Senescent Sloth', username: 'Sloth' , profileLink: "www.steam.com/user_id/Sloth"},
    { id: 99920, name: 'Tumultuous Terrapin', username: 'Terrapin' , profileLink: "www.steam.com/user_id/Terrapin"},
    { id: 99921, name: 'Unassailable Urial', username: 'Urial' , profileLink: "www.steam.com/user_id/Urial"},
    { id: 99922, name: 'Voracious Viscacha', username: 'Viscacha' , profileLink: "www.steam.com/user_id/Viscacha"},
    { id: 99923, name: 'Wondering Wombat', username: 'Wombat' , profileLink: "www.steam.com/user_id/Wombat"},
    { id: 99924, name: 'Xenial Xerus', username: 'Xerus' , profileLink: "www.steam.com/user_id/Xerus"},
    { id: 99925, name: 'Yielding Yak', username: 'Yak' , profileLink: "www.steam.com/user_id/Yak"},
    { id: 99926, name: 'Zaftig Zebu', username: 'Zebu' , profileLink: "www.steam.com/user_id/Zebu"}
  ])
}
