exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("games")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("games").insert([
        {
          user_id: 99901,
          title: "Aardvark",
          description: "Aardvark goes on an adventure",
          time_played: "1",
          all_reviews: "Mostly Positive",
          recent_reviews: "Mixed",
        },
        {
          user_id: 99902,
          title: "Baboon",
          description: "Baboon goes on an adventure",
          time_played: "2",
          all_reviews: "Mostly Positive",
          recent_reviews: "Mixed",
        },
        {
          user_id: 99903,
          title: "Capybara",
          description: "Capybara goes on an adventure",
          time_played: "3",
          all_reviews: "Mostly Positive",
          recent_reviews: "Mixed",
        },
        {
          user_id: 99904,
          title: "Duck",
          description: "Duck goes on an adventure",
          time_played: "4",
          all_reviews: "Mostly Positive",
          recent_reviews: "Mixed",
        },
        {
          user_id: 99905,
          title: "Elephant",
          description: "Elephant goes on an adventure",
          time_played: "5",
          all_reviews: "Mostly Positive",
          recent_reviews: "Mixed",
        },
        {
          user_id: 99906,
          title: "Fox",
          description: "Fox goes on an adventure",
          time_played: "6",
          all_reviews: "Mostly Positive",
          recent_reviews: "Mixed",
        },
        {
          user_id: 99907,
          title: "Gila",
          description: "Gila goes on an adventure",
          time_played: "7",
          all_reviews: "Mostly Positive",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99908,
          title: "Heron",
          description: "Heron goes on an adventure",
          time_played: "8",
          all_reviews: "Mostly Positive",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99909,
          title: "Impala",
          description: "Impala goes on an adventure",
          time_played: "9",
          all_reviews: "Mostly Positive",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99910,
          title: "Jerboa",
          description: "Jerboa goes on an adventure",
          time_played: "10",
          all_reviews: "Very Positive",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99911,
          title: "Kinkajou",
          description: "Kinkajou goes on an adventure",
          time_played: "20",
          all_reviews: "Very Positive",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99912,
          title: "Lemur",
          description: "Lemur goes on an adventure",
          time_played: "25",
          all_reviews: "Very Positive",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99913,
          title: "Mongoose",
          description: "Mongoose goes on an adventure",
          time_played: "30",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Negative",
        },
        {
          user_id: 99914,
          title: "Nyala",
          description: "Nyala goes on an adventure",
          time_played: "35",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Negative",
        },
        {
          user_id: 99915,
          title: "Ocelot",
          description: "Ocelot goes on an adventure",
          time_played: "40",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Negative",
        },
        {
          user_id: 99916,
          title: "Pangolin",
          description: "Pangolin goes on an adventure",
          time_played: "45",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99917,
          title: "Quokka",
          description: "Quokka goes on an adventure",
          time_played: "50",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99918,
          title: "Rail",
          description: "Rail goes on an adventure",
          time_played: "100",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99919,
          title: "Sloth",
          description: "Sloth goes on an adventure",
          time_played: "200",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99920,
          title: "Terrapin",
          description: "Terrapin goes on an adventure",
          time_played: "300",
          all_reviews: "Very Positive",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99921,
          title: "Urial",
          description: "Urial goes on an adventure",
          time_played: "400",
          all_reviews: "Mixed",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99922,
          title: "Viscacha",
          description: "Viscacha goes on an adventure",
          time_played: "500",
          all_reviews: "Mixed",
          recent_reviews: "Mostly Positive",
        },
        {
          user_id: 99923,
          title: "Wombat",
          description: "Wombat goes on an adventure",
          time_played: "1000",
          all_reviews: "Mixed",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99924,
          title: "Xerus",
          description: "Xerus goes on an adventure",
          time_played: "1500",
          all_reviews: "Mixed",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99925,
          title: "Yak",
          description: "Yak goes on an adventure",
          time_played: "2000",
          all_reviews: "Mixed",
          recent_reviews: "Very Positive",
        },
        {
          user_id: 99926,
          title: "Zebu",
          description: "Zebu goes on an adventure",
          time_played: "3000",
          all_reviews: "Mixed",
          recent_reviews: "Very Positive",
        },
      ]);
    });
};
